export const projects = [
  {
    name: "Budget Buddy",
    overviewtitle: "【概要】",
    overview: "シンプルな家計簿アプリです",
    messagetitle: "【使用技術】",
    message:
      "React / ReactHookForm / TypeScript / MUI / Firebase / Zod / DateFNS",
    githubUrl: "https://github.com/smieanne/budget-buddy-app",
    image: "../../assets/projects/BudgetBuddy.gif",
    category: ["react"],
    projectUrl: "https://budget-buddy-app-eta.vercel.app/",
    deployed: true,
    deployed2: true,
  },
  {
    name: "家計簿",
    overviewtitle: "【概要】",
    overview: "グラフで分析できる家計簿アプリです",
    messagetitle: "【使用技術】",
    message:
      "React / ReactHookForm / TypeScript / MUI / Firebase / Zod / react-chartjs-2 / DateFNS / FullCalendar",
    githubUrl: "https://github.com/smieanne/household-app",
    image: "../../assets/projects/Household.gif",
    category: ["react"],
    projectUrl: "https://householdtypescript-906f7.web.app",
    deployed: true,
    deployed2: true,
  },
  {
    name: "Discordクローン",
    overviewtitle: "【概要】",
    overview: "Discordクローン。チャットアプリです",
    messagetitle: "【使用技術】",
    message: "React / Redux / TypeScript / Firebase",
    githubUrl: "https://github.com/smieanne/discord-clone-udemy",
    image: "../../assets/projects/Discord-clone.gif",
    category: ["react"],
    deployed2: true,
  },
  {
    name: "マイクロブログサイト",
    overviewtitle: "【概要】",
    overview: "記事を投稿、削除できるBlogサイト",
    messagetitle: "【使用技術】",
    message: "Next.js / TypeScript / Supabase / Tailwindcss /MUI",
    githubUrl: "https://github.com/smieanne/next.js13-tailwindcss-udemy-blog",
    image: "../../assets/projects/NextBlogSite.gif",
    category: ["Next.js"],
    deployed2: true,
  },
  {
    name: "飲食店HP",
    overviewtitle: "【概要】",
    overview: "飲食店のHPです",
    messagetitle: "【使用技術】",
    message: "HTML / Sass / JavaScript / jQuery ",
    githubUrl: "https://github.com/smieanne/izakaya_hp",
    image: "../../assets/projects/Izakaya.gif",
    category: ["WebSite"],
    projectUrl: "https://smieanne.github.io/izakaya_hp/",
    deployed: true,
    deployed2: true,
  },
  {
    name: "ノートアプリ",
    overviewtitle: "【概要】",
    overview: "メモの新規作成、編集、削除ができるノートアプリ",
    messagetitle: "【使用技術】",
    message: "React / Hooks",
    githubUrl: "https://github.com/smieanne/noteapp-with-react",
    image: "../../assets/projects/Notememo-app.gif",
    category: ["react"],
    projectUrl: "https://noteapp-with-react-bay.vercel.app/",
    deployed: true,
    deployed2: true,
  },
  {
    name: "ポケモン図鑑",
    overviewtitle: "【概要】",
    overview: "ポケモン図鑑です",
    messagetitle: "【使用技術】",
    message: "React / Hooks",
    image: "../../assets/projects/Pokemon-app.gif",
    category: ["react"],
    githubUrl: "https://github.com/smieanne/pokemon-app",
    projectUrl: "https://pokemon-app-amber-one.vercel.app/",
    deployed: true,
    deployed2: true,
  },
  {
    name: "会員管理システム",
    overviewtitle: "【概要】",
    overview: "お知らせ機能がついた会員管理システム",
    messagetitle: "【使用技術】",
    message: "Java / SpringBoot / Mysql / BootStrap",
    githubUrl: "https://github.com/smieanne/MemberList",
    image: "../../assets/projects/Java_club_member.gif",
    category: ["Other"],
    projectUrl: "http://java.apps.rok.jp:22561/",
    deployed2: true,
  },
  {
    name: "英語学習アプリ",
    overviewtitle: "【概要】",
    overview: "AIに英文を添削してもらうWritingの練習アプリ",
    messagetitle: "【使用技術】",
    message: "html / css / javascript ",
    githubUrl: "",
    image: "../../assets/projects/ChatBot.gif",
    category: ["Other"],
  },
  {
    name: "チャットGPTクローン",
    overviewtitle: "【概要】",
    overview: "ChatGPTクローンです",
    messagetitle: "【使用技術】",
    message: "html / css / javascript",
    githubUrl: "",
    image: "../../assets/projects/Chatgpt-clone.gif",
    category: ["Other"],
  },
  {
    name: "オセロゲーム",
    overviewtitle: "【概要】",
    overview: "二人PLAYのシンプルなオセロゲームです。",
    messagetitle: "【使用技術】",
    message: "Express / html / css / javascript / Typescript / mysql",
    githubUrl: "https://github.com/smieanne/Reversi",
    image: "../../assets/projects/Reversi.gif",
    category: ["Other"],
  },
];
